### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Madji** [SECTHEMALL/secthemall#10]
/opt/secthemall/inc/getcountries.sh: строка 36: [: 1495440477000: ожидается использование унарного оператора
(The use of a unary operator is expected) translate

**Comment by Madji** [comment]
and my node is not displayed in the list of nodes on the site

**Comment by Madji** [comment]
....
 if [ $COUNTRYLASTUPDATE -ne $CLASTUPDATEMS ]; then


i write this
  if [[ $COUNTRYLASTUPDATE -ne $CLASTUPDATEMS ]]; then

**Comment by theMiddleBlue** [comment]
Hi @Madji,

thank you, I'm just testing your pull request and it seems works fine. I've just merged your pull request, could you test it?

thank you very much!

-Andrea

**Comment by Madji** [comment]
Yes of course I checked it. After correction I normally registered in iptables all ip addresses of the blocked country
