### ISSUE TITLE
Bug? or not

### ISSUE THREAD

**Issue by Madji** [SECTHEMALL/secthemall#12]
Apparently something with the interface on the site. The node does not appear in the list. And ostensibly does not send logs. Although in the console all okay. The code did not change, it was done according to the manual. Here I attach screenshots from the site. And apply the work of the console
https://asciinema.org/a/2foy20a716adw6k6vsuh21g5i
![1](https://cloud.githubusercontent.com/assets/2238714/26315976/7dc2d0ba-3f1b-11e7-8cf5-b2a4d396a49a.png)
![2](https://cloud.githubusercontent.com/assets/2238714/26315980/825a112e-3f1b-11e7-91f9-01f00b7b0db2.png)
![3](https://cloud.githubusercontent.com/assets/2238714/26315985/8625bd12-3f1b-11e7-8657-57243ec5544d.png)

**Comment by revelt** [comment]
Just to confirm, I can see my node fine, all seems to by synch'ing OK. Something's wrong with your setup, it's difficult to troubleshoot without access to console and trying setup a-z.

Has it ever worked for you?

**Comment by theMiddleBlue** [comment]
Hi @Madji,

from your asciinema session, it seems that your log files doesn't contains new logs. Have you tried to run the secthemall client and then login to your ssh server?

-Andrea

**Comment by Madji** [comment]
okay 
https://asciinema.org/a/5xz1v2holz1d12d3k6kj7tojp
![1](https://cloud.githubusercontent.com/assets/2238714/26317272/994eb426-3f1f-11e7-81b2-44d77ab48ddc.png)
![2](https://cloud.githubusercontent.com/assets/2238714/26317273/9a7fda78-3f1f-11e7-9e7d-ae0b2f397d2c.png)
![3](https://cloud.githubusercontent.com/assets/2238714/26317278/9c903376-3f1f-11e7-95a8-9a0d834b1adc.png)

**Comment by Madji** [comment]
Well then, what is this? It is clear that the logs from netstat came with srv1 nodes. But the node itself is not listed. And if on the site I add a global ban list for example in the country. The client will work fine and add all the rules to iptables /

**Comment by theMiddleBlue** [comment]
@Madji, it seems a bug, please let me check and I'll back to you soon

**Comment by theMiddleBlue** [comment]
Hi @Madji 

could you please send the following commands and paste here the output?
```bash
cd /opt/secthemall
curl -v -d "a=updates&tz=`cat inc/timezone`&username=`cat inc/username`&apikey=`cat inc/apikey`&alias=`cat inc/alias`&myhostname=`hostname | base64 -w0`&myipaddr=`hostname -I | base64 -w0`&uptime=`uptime | base64 -w0`&issue=`cat /etc/issue | grep '\w' | base64 -w0`&uname=`uname -a | base64 -w0`" https://secthemall.com/api/v1/
```
thanks!

**Comment by Madji** [comment]
root@tex-host  # curl -v -d "a=updates&tz=`cat inc/timezone`&username=`cat inc/username`&apikey=`cat inc/apikey`&alias=`cat inc/alias`&myhostname=`hostname | base64 -w0`&myipaddr=`hostname -I | base64 -w0`&uptime=`uptime | base64 -w0`&issue=`cat /etc/issue | grep '\w' | base64 -w0`&uname=`uname -a | base64 -w0`" https://secthemall.com/api/v1/
* Hostname was NOT found in DNS cache
*   Trying 104.27.142.145...
* Connected to secthemall.com (104.27.142.145) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-ECDSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni135354.cloudflaressl.com
* 	 start date: 2017-05-13 00:00:00 GMT
* 	 expire date: 2017-11-19 23:59:59 GMT
* 	 subjectAltName: secthemall.com matched
* 	 issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
* 	 SSL certificate verify ok.
> POST /api/v1/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: secthemall.com
> Accept: */*
> Content-Length: 555
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 555 out of 555 bytes
< HTTP/1.1 500 Internal Server Error
< Date: Tue, 23 May 2017 05:21:38 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d76961efb8174e5ac9f6053b667d8b11d1495516898; expires=Wed, 23-May-18 05:21:38 GMT; path=/; domain=.secthemall.com; HttpOnly
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
root@tex-host  # curl -v -d "a=updates&tz=`cat inc/timezone`&username=`cat inc/username`&apikey=`cat inc/apikey`&alias=`cat inc/alias`&myhostname=`hostname | base64 -w0`&myipaddr=`hostname -I | base64 -w0`&uptime=`uptime | base64 -w0`&issue=`cat /etc/issue | grep '\w' | base64 -w0`&uname=`uname -a | base64 -w0`" https://secthemall.com/api/v1/
* Hostname was NOT found in DNS cache
*   Trying 104.27.142.145...
* Connected to secthemall.com (104.27.142.145) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-ECDSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni135354.cloudflaressl.com
* 	 start date: 2017-05-13 00:00:00 GMT
* 	 expire date: 2017-11-19 23:59:59 GMT
* 	 subjectAltName: secthemall.com matched
* 	 issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
* 	 SSL certificate verify ok.
> POST /api/v1/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: secthemall.com
> Accept: */*
> Content-Length: 555
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 555 out of 555 bytes
< HTTP/1.1 500 Internal Server Error
< Date: Tue, 23 May 2017 05:21:38 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d76961efb8174e5ac9f6053b667d8b11d1495516898; expires=Wed, 23-May-18 05:21:38 GMT; path=/; domain=.secthemall.com; HttpOnly
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Referrer-Policy: no-referrer
< Strict-Transport-Security: max-age=2592000
* Server cloudflare-nginx is not blacklisted
< Server: cloudflare-nginx
< CF-RAY: 363594fb8f857654-ARN
< 
* Connection #0 to host secthemall.com left intact

**Comment by theMiddleBlue** [comment]
Hi @Madji,

thank you for your test. The problem is that the `updates` action returns a 500 status error. It seems that something in your alias name, hostname or inside the issue file has characters that break the syntax that insert your server info into the database. Could you send the following command and paste here the output?

```bash
cd /opt/secthemall
echo "TimeZone: `cat inc/timezone`" && \
echo "Alias: `cat inc/alias`" && \
echo "Hostname: `hostname | base64 -w0`" && \
echo "IP: `hostname -I | base64 -w0`" && \
echo "Uptime: `uptime | base64 -w0`" && \
echo "Issue: `cat /etc/issue | grep '\w' | base64 -w0`" && \
echo "uname: `uname -a | base64 -w0`"
```
thanks!

-Andrea

**Comment by Madji** [comment]
TimeZone: Europe/Moscow
Alias: srv1
Hostname: dGV4LWhvc3QK
IP: NzcuMzcuMTYwLjE3OCAxMC4wLjAuMiAxOTIuMTY4LjEuMTAwIDE5Mi4xNjguMTIyLjEgZmM3Yjo4NjA5OjM2Nzo1YzhiOjJkMzU6OjEgCg==
Uptime: IDExOjE5OjE5IHVwIDEgZGF5LCAxNTo1MiwgIDIgdXNlcnMsICBsb2FkIGF2ZXJhZ2U6IDAsMDcsIDAsMDksIDAsMDgK
Issue: VWJ1bnR1IDE0LjA0LjUgTFRTIFxuIFxsCg==
uname: TGludXggdGV4LWhvc3QgNC40LjAtNzgtZ2VuZXJpYyAjOTl+MTQuMDQuMi1VYnVudHUgU01QIFRodSBBcHIgMjcgMTg6NDk6NDYgVVRDIDIwMTcgeDg2XzY0IHg4Nl82NCB4ODZfNjQgR05VL0xpbnV4Cg==

**Comment by theMiddleBlue** [comment]
Hi @Madji,

probably I have found the problem, could you run the secthemall client now? 

thanks!

**Comment by theMiddleBlue** [comment]
Ok, I've just seen that your node index is been correctly created. Thank you very much for your support to solve this issue, we have really appreciated it!

**Comment by Madji** [comment]
its work

**Comment by Madji** [comment]
great. in the site my node visible!!

**Comment by theMiddleBlue** [comment]
I close this issue, thanks a lot!
