### ISSUE TITLE
White list

### ISSUE THREAD

**Issue by Madji** [SECTHEMALL/secthemall#13]
Check, please.
If I add ip addresses to the white list, they perfectly synchronize with the firewall. But if after doing this reset iptables, then the black list are perfectly synchronized with the site and the block list , and the white list disappear, and disappear even from the site from the section of my global white list. . I checked 2 times. (I have to add them again each time)

**Comment by theMiddleBlue** [comment]
Hi @Madji,

do you mean that after doing an iptables flush (like `iptables -F`), and then restarting the secthemall bash client, it does not restore your whitelist?

**Comment by Madji** [comment]
Yes, that's what I mean. Moreover, on the site when adding an ip address, it is not saved, but it is automatically synchronized with the bash client on the server. As I see, this bug is that the site does not save whitelist.

**Comment by theMiddleBlue** [comment]
Hi @Madji, 

have you tried to insert the IP address with the CIDR (like /24) or without it (just the IPv4) ?

**Comment by Madji** [comment]
All perfectly. Everything is working. After adding to the site in the white list, the whitelist is saved and perfectly synchronized with the client. Thank you.
...Yes, I inserted an ip address with CIDR
