### ISSUE TITLE
Api white list 

### ISSUE THREAD

**Issue by Madji** [SECTHEMALL/secthemall#15]
/opt/secthemall/secthemall.sh --gwldel 62.148.156.159
+ 14:01:48  OK       Configured TimeZone:  Europe/Moscow 
+ 14:01:48  INFO     SECTHEMALL client is running with PID 3550

And nothing... the website had an address in the white list and remained....
same thing with adding the ip
/opt/secthemall# ./secthemall.sh --gwladd 62.148.156.159
+ 14:06:13  OK       Configured TimeZone:  Europe/Moscow 
+ 14:06:13  INFO     SECTHEMALL client is running with PID 3550

**Comment by Madji** [comment]
![photo_2017-11-06_14-10-46](https://user-images.githubusercontent.com/2238714/32438641-54fd7f3a-c2fc-11e7-8418-9a571e23cad1.jpg)

And the words seems to me a little inappropriate in this context a white sheet ))

**Comment by revelt** [comment]
Good catch! Should we say "22 **whitelisted** IP addresses **in the** global whitelist"?

**Comment by Madji** [comment]
I don't know what should answer. but ip addresses are not added just via shell and script. 
at the same time perfectly added via the web on the website. 
A ban and removal from the ban works perfectly via shell commands and scripts

**Comment by theMiddleBlue** [comment]
Thanks @Madji 

as always, good catch! I've fixed the typo on the web dashboard. I've found the bug on the secthemall bash script, I'll fix it in the next few hours.

thanks for your help.

**Comment by theMiddleBlue** [comment]
Hi @Madji 

I've pushed a fixed version, could you try it?

thanks.

**Comment by Madji** [comment]
./secthemall.sh --gwladd 8.8.8.8
+ 11:14:15  OK       Configured TimeZone:  Europe
+ 11:14:15  INFO     Sending 8.8.8.8 to Global Whitelist...
{
    "ok": "IP trusted"
}
root@tex-host:/opt/secthemall# ./secthemall.sh --gwldel 8.8.8.8
+ 11:14:33  OK       Configured TimeZone:  Europe
+ 11:14:33  INFO     Removing 8.8.8.8 from Global Whitelist...
{
    "ok": "IP removed from all whitelists."
}
Thanks! it`s working.
