### ISSUE TITLE
Cannot add IP to Global Blacklist

### ISSUE THREAD

**Issue by sstativa** [SECTHEMALL/secthemall#18]
Looks like SECTHEMALL server does not work properly. I cannot add IP address in Global Blacklist. 

I've already tried the Dashboard and I also tried to do it directly from my Linux server. 

If I run `./secthemall.sh --gbladd 104.192.0.58` I get response 

```
{
    "error": "IP not banned",
    "debug": {
        "banip": "104.192.0.58"
    }
}
```

**Comment by theMiddleBlue** [comment]
Hi @sstativa ,

Please, send us an e-mail at support@secthemall.com from the e-mail address that you use for login. 

Thank you,
Bye.
