### ISSUE TITLE
Whitelist only approach using a dynamic IP

### ISSUE THREAD

**Issue by ddddgh** [SECTHEMALL/secthemall#5]
How do i perform a Whitelist only approach while using a dynamic IP?

I've found a few online scripts custom made to accept ddns as IP, and then using cron to update.

I wonder if i can use your script to do the same?

**Comment by theMiddleBlue** [comment]
Hi @ddddgh,

this can be an interesting feature for the next secthemall client release. At this moment you can update your whitelist by using our API. In the next days, I'll try to send you a script for doing it automatically.

**Comment by theMiddleBlue** [comment]
@ddddgh: if you want, you can use [this python script](https://github.com/SECTHEMALL/whitelist-dynamic-dns) (or create your own from it) to update your SECTHEMALL whitelist resolving a dynamic hostname. Let me know if it works!
