### ISSUE TITLE
Registered using outlook no email came

### ISSUE THREAD

**Issue by ddddgh** [SECTHEMALL/secthemall#6]
So i used outlook email to register but no email came for confirmation.

**Comment by revelt** [comment]
Might be a deliverability issue too.

**Comment by theMiddleBlue** [comment]
Hi @ddddgh, I think @revelt is right. It could be that many DigitalOcean IPv4 classes were blacklisted to prevent spam. We are looking for an external relay as a service that could be used as MTA by secthemall.com. I hope we'll solve this issue soon.

Let me know if you don't have any other mail account for the registration, I could confirm your account by hand (but it might prevent receiving e-mail notifications).
