### ISSUE TITLE
iptables

### ISSUE THREAD

**Issue by Madji** [SECTHEMALL/secthemall#8]
Do not create a rule "Return from the chain"? Then how does the white or black list work? If there is no return policy. And if I have more rules below in the list?

**Comment by Madji** [comment]
# Generated by iptables-save v1.4.21 on Tue May  2 18:29:36 2017
*filter
:INPUT ACCEPT [3707:1313425]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [3732:1298453]
:fail2ban-SSH - [0:0]
:fail2ban-asterisk - [0:0]
:secthemall-blacklist - [0:0]
:secthemall-whitelist - [0:0]
-A INPUT -j secthemall-whitelist
-A INPUT -j secthemall-blacklist
-A INPUT -s 77.37.161.0/24 -i eth0 -j ACCEPT
-A INPUT -s 85.142.148.80/32 -i eth0 -j ACCEPT
-A INPUT -p udp -m string --string "friendly-scanner" --algo bm --to 65535 -j DROP
-A INPUT -p udp -m string --string "sipvicious" --algo bm --to 65535 -j DROP
-A INPUT -p udp -m string --string "sipsak" --algo bm --to 65535 -j DROP
-A INPUT -p udp -m string --string "iWar" --algo bm --to 65535 -j DROP
-A INPUT -p udp -m string --string "sundayddr" --algo bm --to 65535 -j DROP
-A INPUT -p udp -m string --string "sip-scan" --algo bm --to 65535 -j DROP
-A INPUT -p tcp -m tcp --dport 22 -j fail2ban-SSH
-A INPUT -p tcp -m multiport --dports 5000:65535 -j fail2ban-asterisk
-A INPUT -p udp -m multiport --dports 5000:65535 -j fail2ban-asterisk
-A FORWARD -j secthemall-whitelist
-A FORWARD -j secthemall-blacklist
-A fail2ban-SSH -j RETURN
-A fail2ban-asterisk -j RETURN
-A fail2ban-asterisk -j RETURN
-A secthemall-blacklist -s 103.207.37.198/32 -j DROP
-A secthemall-whitelist -s 85.142.148.80/32 -j ACCEPT
-A secthemall-whitelist -s 77.37.161.0/24 -j ACCEPT
COMMIT
# Completed on Tue May  2 18:29:36 2017
# Generated by iptables-save v1.4.21 on Tue May  2 18:29:36 2017

**Comment by theMiddleBlue** [comment]
@Madji: I don't know if I've understood well your request, anyway the secthemall client creates 2 chains, one for the blacklist and one for the whitelist (lines 7 and 8 of your "cut & paste", respectively called secthemall-blacklist and secthemall-whitelist). These two chains are added on top of the INPUT and of the FORWARD chains. So all IP added or removed from your black or white lists are separated from the default iptables chain.

That means that you can add or remove new INPUT rules without break the secthemall chain.

Hope this can help you :)

**Comment by Madji** [comment]
ok. thanks. I understood

**Comment by Madji** [comment]
okey.
*filter
:INPUT ACCEPT [1384:127477]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [392:146385]
:secthemall-blacklist - [0:0]
:secthemall-whitelist - [0:0]
-A INPUT -j secthemall-whitelist
-A INPUT -j secthemall-blacklist
-A FORWARD -j secthemall-whitelist
-A FORWARD -j secthemall-blacklist
-A secthemall-blacklist -s 94.19.95.236/32 -j DROP
-A secthemall-whitelist -s 77.37.160.178/32 -j ACCEPT
COMMIT
# Completed on Wed May 31 10:10:17 2017

The rule of white list does not make sense. Since skipping the Ip for checking into the black list, the following rule does not work! Since there is no return from the black list validation chain. Should be like this:
:secthemall-blacklist - [0:0]
:secthemall-whitelist - [0:0]
:FORWARD ACCEPT [0:0]
-A INPUT -j secthemall-whitelist
-A INPUT -j secthemall-blacklist
-A FORWARD -j secthemall-whitelist
-A FORWARD -j secthemall-blacklist
-A secthemall-blacklist -s 188.19.171.157/32 -j DROP
-A secthemall-blacklist -j RETURN
-A secthemall-whitelist -s 77.37.160.178/32 -j ACCEPT
-A secthemall-whitelist -j RETURN
Without returning from the chain of the black list, the test simply logs into it. And the next rule about the white list is invalid.

**Comment by theMiddleBlue** [comment]
Hi @Madji,

thank you, it seems legit! I'll test this configuration and, if it work as expected, i'll commit a new version of the bash client.

**Comment by theMiddleBlue** [comment]
@Madji I've tested it:

**video:**
[![test](https://img.youtube.com/vi/YlKsza3AXqk/0.jpg)](https://www.youtube.com/watch?v=YlKsza3AXqk)

the `ACCEPT` action should stop the chain evaluation, and the whitelist comes before the blacklist. As you can see, in my setup it seems work as expected without the `RETURN` action. What I've done in the video is: 

- ping my server
- add my ip address in blacklist
- ping can't reach my server anymore
- add my ip in whitelist
- ping start to reach my server again

From the iptables man page: *A firewall rule specifies criteria for a packet and a target. If the packet does not match, the next rule in the chain is the examined; if it does match, then the next rule is specified by the value of the target, which can be the name of a user-defined chain or one of the special values `ACCEPT`, `DROP`, `REJECT`, `QUEUE` or `RETURN`.*

If you could get me more information about your issue, i can do more tests

-theMiddle

**Comment by Madji** [comment]
It's not a mistake but a question. Most likely it's about understanding the work of the iptabes principles. I always believed that there should always be a return from the verification chain. So I thought correctly. So in many manuals and examples
Iptables -N <name>
Iptables -A <name> -j RETURN
Iptables -I <chain> -p <protocol> -j <name>.
Therefore, I rediscovered the topic with the label question. If this rule is not at all necessary in iptables, then the question itself can be considered closed. Thanks for a visual example. 
Sincerely, Madji
