### ISSUE TITLE
SSH Brute force and SECTHEMALL lists not applied

### ISSUE THREAD

**Issue by drigolin** [SECTHEMALL/secthemall#9]
Hi I have subscribed to SSH Brute force black list and to SECTHEMALL black lists but those IPs aren't banned on my node. Do we have to do something specific on the node configuration?

**Comment by theMiddleBlue** [comment]
Hi @drigolin, hope that you have closed this issue because it's self-solved. Anyway if you need more help or information, please don't hesitate to contact us or to open a new issue :)

thanks.

**Comment by drigolin** [comment]
Yes. From my understanding if I add a blacklist all entries aren't banned on the hosts but host are banned if they try contact the server. My guess was that blacklist is applied immediatelly.

**Comment by theMiddleBlue** [comment]
Hi @drigolin,

it should work exactly as you said, when you subscribe the secthemall blacklist all hosts will be added to your blacklist, then the bash client synchronize it on your servers. For example, the "SSH Brute Force Attackers" actually has 163 entries that you should see on your List -> My Blacklist

If that's not the case, let me check that it's not a related to a bug.

thanks!
